### ISSUE TITLE
Question on speed?

### ISSUE THREAD

**Issue by shams-ahmed** [dfreniche/xc-launch#1]
what speed improvement have you noticed? like in seconds?

**Comment by dfreniche** [comment]
I haven't timed it. Maybe using `time` and `xcodebuild` from command line with the same project, on average would be a good measure. But I use this script mainly because everything gets created in memory:
- less stress put on my SSD
- no GB lost somewhere else in my HD

**Comment by shams-ahmed** [comment]
thanks!
